root = "."                           # Directorio raíz de tu proyecto
tmp_dir = "tmp"                      # Directorio temporal donde air almacenará los archivos temporales
include_ext = ["go"]
exclude_dir = ["tmp"]

# Comando para compilar tu aplicación y generar el binario en tmp/main
build.cmd = "go build -buildvcs=false -o tmp/main ./cmd"

# Especifica el binario que air debe ejecutar
build.bin = "tmp/main"

watch_dir = ["api", "workers", "tcp"]
